name: fast_barcode_scanner_new
description: A fast barcode scanner using MLKit on Android and AVFoundation on iOS.
version: 1.1.6

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  fast_barcode_scanner_platform_interface: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.jhoogstraat.fast_barcode_scanner
        pluginClass: FastBarcodeScannerPlugin
      ios:
        pluginClass: FastBarcodeScannerPlugin
